// === Chapitre 1 — PR & Communication : Fondations des relations presse ===
// 12 fiches (4 sujets × 3 niveaux)
export const chapitre1PR = [
  {
    slug: "pr-deb-ecosysteme-media",
    theme: "pr",
    chapitre: 1,
    sujet: "ecosysteme-media",
    semaine: 1,
    niveau: "debutant",
    name: "Comprendre l'écosystème média",
    desc: "Générateur de plan média : identifier earned, owned, paid et prioriser ses cibles.",
    duree: "14 min",
    htmlFile: "/pr-deb-ecosysteme-media.html",
    image: "/pr-media-1.jpg",
  },
  {
    slug: "pr-int-ecosysteme-media",
    theme: "pr",
    chapitre: 1,
    sujet: "ecosysteme-media",
    semaine: 1,
    niveau: "intermediaire",
    name: "Arbitrer son mix média",
    desc: "Répartiteur earned/owned/paid : classer ses actions et équilibrer son mix.",
    duree: "15 min",
    htmlFile: "/pr-int-ecosysteme-media.html",
    image: "/pr-media-2.jpg",
  },
  {
    slug: "pr-exp-ecosysteme-media",
    theme: "pr",
    chapitre: 1,
    sujet: "ecosysteme-media",
    semaine: 1,
    niveau: "expert",
    name: "Modéliser le rendement RP",
    desc: "Simulateur de pitch : tester son angle sur un journaliste et obtenir un pitch prêt à l'emploi.",
    duree: "18 min",
    htmlFile: "/pr-exp-ecosysteme-media.html",
    image: "/pr-media-3.jpg",
  },
  {
    slug: "pr-deb-message-cle",
    theme: "pr",
    chapitre: 1,
    sujet: "message-cle",
    semaine: 2,
    niveau: "debutant",
    name: "Construire son message",
    desc: "Générateur de message clé : assembler qui, quoi, preuve et bénéfice en une phrase forte.",
    duree: "13 min",
    htmlFile: "/pr-deb-message-cle.html",
    image: "/pr-message-1.jpg",
  },
  {
    slug: "pr-int-message-cle",
    theme: "pr",
    chapitre: 1,
    sujet: "message-cle",
    semaine: 2,
    niveau: "intermediaire",
    name: "Structurer son message en pyramide",
    desc: "Arbitre de formulations : hiérarchiser ses idées selon la pyramide inversée.",
    duree: "15 min",
    htmlFile: "/pr-int-message-cle.html",
    image: "/pr-message-2.jpg",
  },
  {
    slug: "pr-exp-message-cle",
    theme: "pr",
    chapitre: 1,
    sujet: "message-cle",
    semaine: 2,
    niveau: "expert",
    name: "Adapter son message par audience",
    desc: "Simulateur d'interview presse : tenir son message face aux questions pièges.",
    duree: "17 min",
    htmlFile: "/pr-exp-message-cle.html",
    image: "/pr-message-3.jpg",
  },
  {
    slug: "pr-deb-communique-pitch",
    theme: "pr",
    chapitre: 1,
    sujet: "communique-pitch",
    semaine: 3,
    niveau: "debutant",
    name: "Structurer un communiqué",
    desc: "Générateur de communiqué : titre, accroche 5W, corps, citation et boilerplate.",
    duree: "14 min",
    htmlFile: "/pr-deb-communique-pitch.html",
    image: "/pr-communique-1.jpg",
  },
  {
    slug: "pr-int-communique-pitch",
    theme: "pr",
    chapitre: 1,
    sujet: "communique-pitch",
    semaine: 3,
    niveau: "intermediaire",
    name: "Affûter titre et accroche",
    desc: "Atelier d'écriture : analyser son titre et son accroche selon cinq critères objectifs.",
    duree: "15 min",
    htmlFile: "/pr-int-communique-pitch.html",
    image: "/pr-communique-2.jpg",
  },
  {
    slug: "pr-exp-communique-pitch",
    theme: "pr",
    chapitre: 1,
    sujet: "communique-pitch",
    semaine: 3,
    niveau: "expert",
    name: "Planifier sa diffusion",
    desc: "Planificateur de diffusion : bâtir un rétroplanning daté et éviter les pièges de timing.",
    duree: "17 min",
    htmlFile: "/pr-exp-communique-pitch.html",
    image: "/pr-communique-3.jpg",
  },
  {
    slug: "pr-deb-mesurer-retombees",
    theme: "pr",
    chapitre: 1,
    sujet: "mesurer-retombees",
    semaine: 4,
    niveau: "debutant",
    name: "Mesurer ses retombées",
    desc: "Tableau de bord de retombées : compter, qualifier par type et tonalité, lire sa couverture.",
    duree: "13 min",
    htmlFile: "/pr-deb-mesurer-retombees.html",
    image: "/pr-mesure-1.jpg",
  },
  {
    slug: "pr-int-mesurer-retombees",
    theme: "pr",
    chapitre: 1,
    sujet: "mesurer-retombees",
    semaine: 4,
    niveau: "intermediaire",
    name: "Les bons indicateurs",
    desc: "Hiérarchiseur de KPIs : distinguer indicateurs de valeur et chiffres de vanité.",
    duree: "15 min",
    htmlFile: "/pr-int-mesurer-retombees.html",
    image: "/pr-mesure-2.jpg",
  },
  {
    slug: "pr-exp-mesurer-retombees",
    theme: "pr",
    chapitre: 1,
    sujet: "mesurer-retombees",
    semaine: 4,
    niveau: "expert",
    name: "Cadrer avant de lancer",
    desc: "Fixeur d'objectifs + KPIs : définir objectif, indicateurs et cibles avant la campagne.",
    duree: "16 min",
    htmlFile: "/pr-exp-mesurer-retombees.html",
    image: "/pr-mesure-3.jpg",
  },
];
